sudo: false
language: node_js
node_js:
- '8'

script:
- npm test
- npm pack


deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: h9ZyUSZ8tTzRmc5cFVO6wpbC2VM1TrxQ3mMDnVquPIEtpfSyyBUGxPAdM4Xlnqcoot2hJ7RoGIGmaGHInlzuHcs8D7Y+jZtuW9m9nL0+omekK7sKsPhIItd0wEV6wG3nwUkuwgOE4gk3TjtgOXyVptej7GKG+G/Lk6vuP/sY54uErBdFafeaLY26KbfP+kzqaaireTy4tjuxwWxUvVimw4YXsqvF1ziD7IHoQKZrwG+g4ggoba4rn1LyOmgzX+lJ7abtrNVBXZSMC/XdcjEpkoAgDdhngj33nx/tiyyXcbQfDfLXu/t2iwLYYHS/ZN6pLxtLputppylo8/Hgt0TDscCYj4l78UOYq5ImfKLuUhCX38/OLWLIjtcKheVRmzX7WmPjmClJI/dQvrNfOnhr3rjTjuWKgZOqKY9Ul/i4oCGYmRWrLPMKhqKnInzYWQsQ+ytnxlg3INcJafpQfGUVKCkti0iTNjGe/wuY2WvuH8dE5KFw9rmKd9YGIG+R7FNP6nqG668uDaJIezmGuCW/8pp51pLd5YZ+XW96qUR6ruYh76LkD20LqtnojXB8BDkUAEW5xDb2pNTLvGmC40p5ihP14Rq9RfcAdSs6O9g+8YGOWUsajfARpGoZ7lRCj/oYmvDmJUDk411Z7Niofjj8MMOKu0Y8yqe0mhmSKVIOEZ4=
  file: 
  - prop-parser-0.1.0.tgz
  - dist/prop-parser.js  
  - dist/prop-parser.min.js
  on:
    repo: arranstewart/prop-parser-js
    tags: true
